packages:
  # all packages in direct subdirs of packages/
  - 'core/packages/*'
  - 'packages/volto-procergs-sitebase'
  - 'packages/volto-custom-light-theme/packages/volto-custom-light-theme'
  - 'packages/volto-site-componentes/packages/volto-site-componentes'
  - 'packages/volto-dsgvo-banner/packages/volto-dsgvo-banner'
